name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install GDAL and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Install Python packages
      run: |
        pip install kivy[base] kivy_deps.angle kivy_deps.sdl2 kivy_deps.glew
        pip install pyinstaller
        pip install httpx parsel jmespath aiofiles aiohttp
        pip install matplotlib geopandas shapely
        pip install typing_extensions

    - name: Build executable
      shell: cmd
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      run: |
        pyinstaller --name RightmoveGuesser --onefile --windowed kivy_app.py --hidden-import="pkg_resources.py2_warn" --hidden-import="shapely.geometry" --hidden-import="geopandas"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RightmoveGuesser-windows
        path: dist/
