name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy[base] kivy_deps.angle kivy_deps.sdl2 kivy_deps.glew
        pip install pyinstaller
        pip install httpx parsel jmespath aiofiles aiohttp
        
    - name: Build executable
      shell: cmd
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      run: |
        python -c "import kivy_deps, os; print('KIVY_DEPS_PATH=' + os.path.dirname(kivy_deps.__file__))" >> $GITHUB_ENV
        pyinstaller --name RightmoveGuesser --onefile --windowed --collect-submodules kivy --hidden-import "win32timezone" main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RightmoveGuesser-windows
        path: dist/