name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy[base] kivy_deps.angle kivy_deps.sdl2 kivy_deps.glew
        pip install pyinstaller
        pip install httpx
        pip install parsel
        pip install jmespath
        pip install aiofiles
        pip install aiohttp
        
    - name: Build executable
      env:
        KIVY_GL_BACKEND: 'angle_sdl2'
      run: |
        pyinstaller --name RightmoveGuesser --onefile --windowed ^
        --add-data "C:\hostedtoolcache\windows\Python\3.9.13\x64\share\glew;share\glew" ^
        --add-data "C:\hostedtoolcache\windows\Python\3.9.13\x64\share\sdl2;share\sdl2" ^
        --add-data "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\kivy_deps.angle;kivy_deps.angle" ^
        --add-data "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\kivy_deps.sdl2;kivy_deps.sdl2" ^
        --add-data "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\kivy_deps.glew;kivy_deps.glew" ^
        --hidden-import kivy ^
        --hidden-import kivy.deps.sdl2 ^
        --hidden-import kivy.deps.glew ^
        --hidden-import kivy.deps.angle ^
        --hidden-import kivy.factory_registers ^
        --hidden-import kivy.graphics ^
        main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: RightmoveGuesser-windows
        path: dist/